# Generated by Django 5.2.1 on 2025-05-22 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('cancelled', 'Cancelled')], default='pending', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('provider', 'date', 'time')},
        ),
    ]
